// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbgfclxksreieyapmxml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZ2ZjbHhrc3JlaWV5YXBteG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTQ4MjMsImV4cCI6MjA3MTY3MDgyM30.S2ON-BSMZMsgrTiwIeuLu7gs_BcEJuPY6w-3rd7x1i4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});